### ISSUE TITLE
Add support for multiple types during each step

### ISSUE THREAD

**Issue by ragingpastry** [AFCYBER-DREAM/piedpiper-picli#27]
It would be useful to allow the user to specify a list when calling out which function to use for each step.

One example would be SAST for python. Mypy and bandit are both considered SAST, but under the current framework we cannot run both tools. This should be a fairly easy change. We would simply build up a list (or specify a list directly in the vars) and then iterate that list under each command

**Comment by codrcodz** [comment]
Hmm. I can see the benefit. Would the parameter always be a list then? And would all the parameter names be plural (i.e. "linters" vs "linter") for consistency?

**Comment by ragingpastry** [comment]
I think that would probably be the cleanest way to handle it. That should allow for expansion in the future for other weird scenarios where one language has multiple used SAST tools or build tools, or whatever else

**Comment by ragingpastry** [comment]
Not applicable anymore
